# Build on OSX and linux (use our docker container)
  
matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      services: docker
    - os: osx
      language: r
      cache: packages
      pandoc_version: 1.17.2
  
env:
 global:
  - REPO=$DOCKER_USER/huskydown
  
warnings_are_errors:  false  

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/fonts  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install font-eb-garamond font-source-code-pro font-lato  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install biblatex titling titlesec quotchap lettrine appendix units tocloft draftwatermark everypage wasysym logreq xstring collection-fontsrecommended texliveonfly   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e 'install.packages("devtools")'  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t $REPO . ; fi

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "devtools::install_github('benmarwick/huskydown')" ; fi
  # remove pre-built PDF,
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "unlink('index', recursive = TRUE)" ; fi
  # make a PhD thesis from the template
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "rmarkdown::draft('index.Rmd', template = 'thesis', package = 'huskydown', create_dir = TRUE, edit = FALSE)"  ; fi 
  #  render new thesis into a PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "setwd('index'); bookdown::render_book('index.Rmd', huskydown::thesis_pdf(latex_engine = 'xelatex'))"  ; fi
  #  check that we got a PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "file.exists('index/_book/thesis.pdf')"  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R -e "file.info('index/_book/thesis.pdf')"  ; fi
 

# push our custom docker container to docker hub, env vars stored on travis-ci.org
# don't forget to set these at https://travis-ci.org/.../...settings
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export REPO=$DOCKER_USER/huskydown ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f Dockerfile -t $REPO:$COMMIT . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker tag $REPO:$COMMIT $REPO:$TAG ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker push $REPO ; fi
 


  



